<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDdKoTib\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDdKoTib/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDdKoTib.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDdKoTib\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDdKoTib\App_KernelDevDebugContainer([
    'container.build_hash' => 'DdKoTib',
    'container.build_id' => '1051d48e',
    'container.build_time' => 1791121981,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDdKoTib');
