<?php

namespace ContainerDEnJBqX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerStorageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\CustomerStorage' shared autowired service.
     *
     * @return \App\Service\CustomerStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/CustomerStorage.php';

        return $container->privates['App\\Service\\CustomerStorage'] = new \App\Service\CustomerStorage((\dirname(__DIR__, 3).'/data/customers.json'));
    }
}
