<?php

namespace ContainerDEnJBqX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_ViolationMapperService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'form.violation_mapper' shared service.
     *
     * @return \Symfony\Component\Form\Extension\Validator\ViolationMapper\ViolationMapper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/Validator/ViolationMapper/ViolationMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/Validator/ViolationMapper/ViolationMapper.php';

        return $container->privates['form.violation_mapper'] = new \Symfony\Component\Form\Extension\Validator\ViolationMapper\ViolationMapper(($container->privates['twig.form.renderer'] ?? $container->load('getTwig_Form_RendererService')), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
