<?php

namespace ContainerDEnJBqX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_TypeGuesser_EnumTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'form.type_guesser.enum_type' shared service.
     *
     * @return \Symfony\Component\Form\EnumFormTypeGuesser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeGuesserInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/EnumFormTypeGuesser.php';

        return $container->privates['form.type_guesser.enum_type'] = new \Symfony\Component\Form\EnumFormTypeGuesser();
    }
}
