<?php

namespace ContainerDEnJBqX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_SerializerLocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'messenger.transport.serializer_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['messenger.transport.serializer_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'async' => ['privates', '.signing.messenger.default_serializer', 'get_Signing_Messenger_DefaultSerializerService', true],
            'failed' => ['privates', '.signing.messenger.default_serializer', 'get_Signing_Messenger_DefaultSerializerService', true],
        ], [
            'async' => '?',
            'failed' => '?',
        ]);
    }
}
