<?php

namespace ContainerDEnJBqX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPriceListControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\PriceListController' shared autowired service.
     *
     * @return \App\Controller\PriceListController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/PriceListController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PriceListStorage.php';

        return $container->services['App\\Controller\\PriceListController'] = new \App\Controller\PriceListController(($container->privates['App\\Service\\PriceListStorage'] ??= new \App\Service\PriceListStorage((\dirname(__DIR__, 3).'/data/price-list.json'))));
    }
}
