<?php

namespace ContainerDdKoTib;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Debug_Console_ValueResolver_Doctrine_Orm_EntityValueResolver_ConsoleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.debug.console.value_resolver.doctrine.orm.entity_value_resolver.console' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\ValueResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/TraceableValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/ArgumentResolver/EntityValueResolverTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/ArgumentResolver/Console/EntityValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Attribute/ValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/Attribute/MapEntity.php';

        return $container->privates['.debug.console.value_resolver.doctrine.orm.entity_value_resolver.console'] = new \Symfony\Component\Console\ArgumentResolver\ValueResolver\TraceableValueResolver(new \Symfony\Bridge\Doctrine\ArgumentResolver\Console\EntityValueResolver(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['doctrine.orm.entity_value_resolver.expression_language'] ??= new \Symfony\Component\ExpressionLanguage\ExpressionLanguage()), new \Symfony\Bridge\Doctrine\Attribute\MapEntity(evictCache: NULL, disabled: false), []), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
    }
}
