<?php

namespace ContainerDdKoTib;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_Doctrine_PgNotifyOnIdleListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.transport.doctrine.pg_notify_on_idle_listener' shared service.
     *
     * @return \Symfony\Component\Messenger\Bridge\Doctrine\EventListener\PostgreSqlNotifyOnIdleListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-messenger/EventListener/PostgreSqlNotifyOnIdleListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/clock/src/ClockInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/clock/ClockInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/clock/Clock.php';

        return $container->privates['messenger.transport.doctrine.pg_notify_on_idle_listener'] = new \Symfony\Component\Messenger\Bridge\Doctrine\EventListener\PostgreSqlNotifyOnIdleListener(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['clock'] ??= new \Symfony\Component\Clock\Clock()));
    }
}
