<?php

namespace ContainerDdKoTib;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_HandlerLifecycleManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'monolog.handler_lifecycle_manager' shared service.
     *
     * @return \Symfony\Bundle\MonologBundle\HandlerLifecycleManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/monolog-bundle/src/HandlerLifecycleManager.php';

        return $container->services['monolog.handler_lifecycle_manager'] = new \Symfony\Bundle\MonologBundle\HandlerLifecycleManager(new RewindableGenerator(function () use ($container) {
            if (isset($container->privates['monolog.handler.main'])) {
                yield 0 => ($container->privates['monolog.handler.main'] ?? null);
            }
            if (isset($container->privates['monolog.handler.console'])) {
                yield 1 => ($container->privates['monolog.handler.console'] ?? null);
            }
        }, fn () => 0 + (int) (isset($container->privates['monolog.handler.main'])) + (int) (isset($container->privates['monolog.handler.console']))));
    }
}
