<?php

namespace ContainerDdKoTib;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPriceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PriceController' shared autowired service.
     *
     * @return \App\Controller\PriceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/PriceController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PricingService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CustomerStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Service/OrderStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PriceListStorage.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/clock/src/ClockInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/clock/ClockInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/clock/Clock.php';

        return $container->services['App\\Controller\\PriceController'] = new \App\Controller\PriceController(new \App\Service\PricingService(($container->privates['App\\Service\\PriceListStorage'] ??= new \App\Service\PriceListStorage((\dirname(__DIR__, 3).'/data/price-list.json'))), ($container->privates['clock'] ??= new \Symfony\Component\Clock\Clock())), new \App\Service\CustomerStorage((\dirname(__DIR__, 3).'/data/customers.json')), new \App\Service\OrderStorage((\dirname(__DIR__, 3).'/data/orders.json')), ($container->privates['debug.validator'] ?? self::getDebug_ValidatorService($container)));
    }
}
