<?php

namespace ContainerFb6Wypj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Debug_Console_ValueResolver_Doctrine_Orm_EntityValueResolver_ConsoleService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.debug.console.value_resolver.doctrine.orm.entity_value_resolver.console' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\ValueResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/TraceableValueResolver.php';

        return $container->privates['.debug.console.value_resolver.doctrine.orm.entity_value_resolver.console'] = new \Symfony\Component\Console\ArgumentResolver\ValueResolver\TraceableValueResolver(($container->privates['doctrine.orm.entity_value_resolver.console'] ?? $container->load('getDoctrine_Orm_EntityValueResolver_ConsoleService')), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
    }
}
