<?php

namespace ContainerFb6Wypj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Orm_EntityValueResolver_ConsoleService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.orm.entity_value_resolver.console' shared service.
     *
     * @return \Symfony\Bridge\Doctrine\ArgumentResolver\Console\EntityValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/ArgumentResolver/EntityValueResolverTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/ArgumentResolver/Console/EntityValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Attribute/ValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/Attribute/MapEntity.php';

        return $container->privates['doctrine.orm.entity_value_resolver.console'] = new \Symfony\Bridge\Doctrine\ArgumentResolver\Console\EntityValueResolver(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['doctrine.orm.entity_value_resolver.expression_language'] ??= new \Symfony\Component\ExpressionLanguage\ExpressionLanguage()), new \Symfony\Bridge\Doctrine\Attribute\MapEntity(evictCache: NULL, disabled: false), []);
    }
}
