<?php

namespace ContainerFb6Wypj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_RunSqlCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'doctrine.run_sql_command' shared service.
     *
     * @return \Doctrine\DBAL\Tools\Console\Command\RunSqlCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/dbal/src/Tools/Console/Command/RunSqlCommand.php';

        $instance = new \Doctrine\DBAL\Tools\Console\Command\RunSqlCommand(($container->privates['doctrine.manager_registry_aware_connection_provider'] ?? $container->load('getDoctrine_ManagerRegistryAwareConnectionProviderService')));

        $instance->setName('dbal:run-sql');

        return $container->privates['doctrine.run_sql_command'] = $instance;
    }
}
