<?php

namespace ContainerFb6Wypj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Bus_Default_Middleware_HandleMessageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'messenger.bus.default.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/clock/src/ClockInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/clock/ClockInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/clock/Clock.php';

        try {
            $a = ($container->privates['messenger.bus.default.messenger.handlers_locator'] ?? $container->load('getMessenger_Bus_Default_Messenger_HandlersLocatorService'));

            if (isset($container->privates['messenger.bus.default.middleware.handle_message'])) {
                return $container->privates['messenger.bus.default.middleware.handle_message'];
            }

            $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware($a, false, ($container->privates['clock'] ??= new \Symfony\Component\Clock\Clock()));

            if (isset($container->privates['messenger.bus.default.middleware.handle_message'])) {
                return $container->privates['messenger.bus.default.middleware.handle_message'];
            }

            $container->privates['messenger.bus.default.middleware.handle_message'] = $instance;

            $instance->setLogger(($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));

            return $instance;
        } catch (\Throwable $e) {
            unset($container->privates['messenger.bus.default.middleware.handle_message']);

            throw $e;
        }
    }
}
