<?php

namespace ContainerFb6Wypj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderStorageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\OrderStorage' shared autowired service.
     *
     * @return \App\Service\OrderStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/OrderStorage.php';

        return $container->privates['App\\Service\\OrderStorage'] = new \App\Service\OrderStorage((\dirname(__DIR__, 3).'/data/orders.json'));
    }
}
