<?php

namespace ContainerFb6Wypj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPricingServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\PricingService' shared autowired service.
     *
     * @return \App\Service\PricingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PricingService.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PriceListStorage.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/clock/src/ClockInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/clock/ClockInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/clock/Clock.php';

        return $container->privates['App\\Service\\PricingService'] = new \App\Service\PricingService(($container->privates['App\\Service\\PriceListStorage'] ??= new \App\Service\PriceListStorage((\dirname(__DIR__, 3).'/data/price-list.json'))), ($container->privates['clock'] ??= new \Symfony\Component\Clock\Clock()));
    }
}
