<?php

namespace ContainerFb6Wypj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPriceControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\PriceController' shared autowired service.
     *
     * @return \App\Controller\PriceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/PriceController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CustomerStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Service/OrderStorage.php';

        return $container->services['App\\Controller\\PriceController'] = new \App\Controller\PriceController(($container->privates['App\\Service\\PricingService'] ?? $container->load('getPricingServiceService')), ($container->privates['App\\Service\\CustomerStorage'] ??= new \App\Service\CustomerStorage((\dirname(__DIR__, 3).'/data/customers.json'))), ($container->privates['App\\Service\\OrderStorage'] ??= new \App\Service\OrderStorage((\dirname(__DIR__, 3).'/data/orders.json'))), ($container->privates['debug.validator'] ?? self::getDebug_ValidatorService($container)));
    }
}
