<?php

namespace ContainerFb6Wypj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Csrf_SameOriginTokenManagerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.csrf.same_origin_token_manager' shared service.
     *
     * @return \Symfony\Component\Security\Csrf\SameOriginCsrfTokenManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-csrf/CsrfTokenManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-csrf/SameOriginCsrfTokenManager.php';

        return $container->privates['security.csrf.same_origin_token_manager'] = new \Symfony\Component\Security\Csrf\SameOriginCsrfTokenManager(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['monolog.logger.request'] ?? self::getMonolog_Logger_RequestService($container)), ($container->privates['security.csrf.same_origin_token_manager.inner'] ?? $container->load('getSecurity_Csrf_SameOriginTokenManager_InnerService')), ['submit', 'authenticate', 'logout'], true, 'csrf-token');
    }
}
