<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFb6Wypj\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFb6Wypj/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFb6Wypj.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFb6Wypj\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerFb6Wypj\App_KernelTestDebugContainer([
    'container.build_hash' => 'Fb6Wypj',
    'container.build_id' => '59db8ae8',
    'container.build_time' => 1791117788,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFb6Wypj');
